server:
  port: 8080
  servlet:
    context-path: /peoplemanager

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: peoplemanager
        trace: true
      path: /database_config

application:
  description: Projeto desenvolvido no Bootcamp GFT Start ## 2Java
  version: 0.0.1-EOS
